### ISSUE TITLE
AnonymousTypeUtils breaks with a large number of properties.

### ISSUE THREAD

**Issue by 2222222** [dotlattice/LatticeUtils#1]
Not sure if the problem is just the number of properties, but here is a test case that breaks it:

``` c#
LatticeUtils.AnonymousTypeUtils.CreateGenericTypeDefinition(new[] { "Property1", "Property2", "Property3", "Property4", "Property5", "Property6", "Property7", "Property8", "Property9", "Property10" });
```

This is the error I get:

```
System.NotSupportedException : Illegal one-byte branch at position: 9. Requested branch was: 192.
Result StackTrace:  
at System.Reflection.Emit.ILGenerator.BakeByteArray()
at System.Reflection.Emit.MethodBuilder.CreateMethodBodyHelper(ILGenerator il)
at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
at System.Reflection.Emit.TypeBuilder.CreateType()
at LatticeUtils.AnonymousTypeUtils.CreateGenericTypeDefinitionWithoutLockCheck(String genericTypeDefinitionName, ICollection`1 propertyNames, Boolean isMutable)
at LatticeUtils.AnonymousTypeUtils.GetOrCreateGenericTypeDefinition(String genericTypeDefinitionName, ICollection`1 propertyNames, Boolean isMutable)
at LatticeUtils.AnonymousTypeUtils.GetOrCreateGenericTypeDefinition(ICollection`1 propertyNames, Boolean isMutable)
at LatticeUtils.AnonymousTypeUtils.CreateType(IEnumerable`1 typePairs, Boolean isMutable)
at LatticeUtils.AnonymousTypeUtils.CreateType(IEnumerable`1 typePairs)
...
```

**Comment by dotlattice** [comment]
Thanks for the test case.  The problem was with generating the IL for the Equals method when there are more than five properties.

I put a fix in for version 2.0.0.3, and I updated the nuget package to this version.
